#ifndef __SIG_H__
#define __SIG_H__

#include <signal.h>

#define SIG_OPE_REQ_TO_2 (SIGRTMIN + 1)
#define SIG_OPE_REQ_TO_3 (SIGRTMIN + 2)
#define SIG_OPE_REQ_TO_4 (SIGRTMIN + 3)
#define SIG_OPE_REQ_TO_5 (SIGRTMIN + 4)

#define SIG_OPE_REQ_TO_2_DONE (SIGRTMIN + 5)
#define SIG_OPE_REQ_TO_3_DONE (SIGRTMIN + 6)
#define SIG_OPE_REQ_TO_4_DONE (SIGRTMIN + 7)
#define SIG_OPE_REQ_TO_5_DONE (SIGRTMIN + 8)

#define SIG_OPX_UPDATE_LIGHT (SIGRTMIN + 9)

#define SIG_MNG_MOVE_LIFT_TO_1 (SIGRTMIN + 10)
#define SIG_MNG_MOVE_LIFT_TO_2 (SIGRTMIN + 11)
#define SIG_MNG_MOVE_LIFT_TO_3 (SIGRTMIN + 12)
#define SIG_MNG_MOVE_LIFT_TO_4 (SIGRTMIN + 13)
#define SIG_MNG_MOVE_LIFT_TO_5 (SIGRTMIN + 14)

#define SIG_CTRL_MOVE_LIFT_UP      (SIGRTMIN + 15)
#define SIG_CTRL_MOVE_LIFT_DOWN    (SIGRTMIN + 16)
#define SIG_CTRL_MOVE_LIFT_STOP    (SIGRTMIN + 17)
#define SIG_CTRL_MOVE_LIFT_ARRIVED (SIGRTMIN + 18)

#define SIG_LIFT_MOVE_OK      (SIGRTMIN + 19)
#define SIG_LIFT_MOVE_STOPPED (SIGRTMIN + 20)

#define SIG_SEN_ON  (SIGRTMIN + 21)
#define SIG_SEN_OFF (SIGRTMIN + 22)
#define SIG_SEN_ERR (SIGRTMIN + 23)

#endif
