#ifndef __SIG_H__
#define __SIG_H__

#include <signal.h>

#define SIG_OPE_REQ_TO_2 SIGRTMIN + 1
#define SIG_OPE_REQ_TO_3 SIGRTMIN + 2
#define SIG_OPE_REQ_TO_4 SIGRTMIN + 3
#define SIG_OPE_REQ_TO_5 SIGRTMIN + 4

#define SIG_OPX_UPDATE_LIGHT SIGRTMIN + 5

#define SIG_MNG_MOVE_LIFT_UP   SIGRTMIN + 6
#define SIG_MNG_MOVE_LIFT_DOWN SIGRTMIN + 7
#define SIG_MNG_MOVE_LIFT_STOP SIGRTMIN + 8

#define SIG_CTRL_MOVE_LIFT_UP      SIGRTMIN + 10
#define SIG_CTRL_MOVE_LIFT_DOWN    SIGRTMIN + 11
#define SIG_CTRL_MOVE_LIFT_STOP    SIGRTMIN + 12
#define SIG_CTRL_MOVE_LIFT_OK      SIGRTMIN + 13
#define SIG_CTRL_MOVE_LIFT_ARRIVED SIGRTMIN + 14

#define SIG_LIFT_MOVE_OK      SIGRTMIN + 15
#define SIG_LIFT_MOVE_STOPPED SIGRTMIN + 16

#define SIG_SEN_ON  SIGRTMIN + 17
#define SIG_SEN_OFF SIGRTMIN + 18

#endif
